matches:
  - triggers: 
    - "\\sys"
    - "\\cases"
    word: true
    replace: "\\begin{cases}\n$|$\n\\end{cases}"

  - triggers: 
    - "\\align"
    - "\\al"
    word: true
    replace: "\\begin{align}\n$|$\n\\end{align}"

  - triggers: 
    - "\\align*"
    - "\\al*"
    word: true
    replace: "\\begin{align*}\n$|$\n\\end{align*}"

  - triggers: 
    - "\\equation"
    - "\\eq"
    word: true
    replace: "\\begin{equation}\n$|$\n\\end{equation}"

  - triggers: 
    - "\\equation*"
    - "\\eq*"
    word: true
    replace: "\\begin{equation*}\n$|$\n\\end{equation*}"

  - triggers: 
    - "\\frac "
    - "\\fr "
    replace: "\\frac{$|$}{}"

  - triggers:
    - "\\d "
    - "\\der "
    replace: "\\frac{d $|$}{d }"
  
  - triggers:
    - "\\p "
    - "\\par "
    replace: "\\frac{\\partial $|$}{\\partial }"

  - triggers:
    - "\\qed"
    word: true
    replace: "\\begin{equation}\\tag*{$\\Box$}\\end{equation}"

  - trigger: "\\R "
    replace: "\\mathbb{R}"

  - trigger: "\\Q "
    replace: "\\mathbb{Q}"
 
  - trigger: "\\H "
    replace: "\\mathbb{H}"
 
  - trigger: "\\C "
    replace: "\\mathbb{C}"
  
  - trigger: "\\K "
    replace: "\\mathbb{K}"

  - trigger: "\\Z "
    replace: "\\mathbb{Z}"

  - trigger: "\\N "
    replace: "\\mathbb{N}"

  - regex: "\\\\mb(?P<char>[A-Za-z]) "
    replace: "\\mathbb{{{char}}}"

  - regex: "\\\\mb "
    replace: "\\mathbb{$|$}"

  - regex: "\\\\mc(?P<char>[A-Za-z]) "
    replace: "\\mathcal{{{char}}}"

  - regex: "\\\\mc "
    replace: "\\mathcal{$|$}"

  - regex: "\\\\mf(?P<char>[A-Za-z]) "
    replace: "\\mathfrak{{{char}}}"

  - regex: "\\\\mf "
    replace: "\\mathfrak{$|$}"

  - regex: "\\\\mr(?P<char>[A-Za-z]) "
    replace: "\\mathscr{{{char}}}"

  - regex: "\\\\mr "
    replace: "\\mathscr{$|$}"

  - trigger: "\\inv "
    replace: "^{-1}"

  - regex: "\\\\hmf(?P<char>[A-Za-z]) "
    replace: "\\hat{\\mathfrak{{{char}}}}"

  - regex: "\\\\hmf "
    replace: "\\hat{\\mathfrak{$|$}}"



  - regex: "\\\\beg\\{(?P<environment>.*)\\}"
    word: true
    replace: "\\begin{{{environment}}}\n$|$\n\\end{{{environment}}}"
  
  - trigger: "\\l "
    replace: "\\left"

  - trigger: "\\r "
    replace: "\\right"

  - trigger: "[[ "
    replace: "\\left["
  
  - trigger: "]] "
    replace: "\\right]"

  - trigger: "[[]] "
    replace: "\\left[ $|$ \\right]"

  - trigger: "(( "
    replace: "\\left("
  
  - trigger: ")) "
    replace: "\\right)"

  - trigger: "(()) "
    replace: "\\left( $|$ \\right)"

  - trigger: "\\lr "
    replace: "\\langle $|$ \\rangle"

  - trigger: "\\LR "
    replace: "\\left\\langle $|$ \\right\\rangle"

  - trigger: "\\t "
    replace: "\\text{$|$}"

  - trigger: "\\t, "
    replace: "\\text{$|$\\,}"

  - regex: "\\\\T(?P<input1>.*) "
    replace: "\\text{{{input1}}}" 
  
  - regex: "\\\\L(?P<input1>.*) "
    replace: "\\text{{{input1}}\\,}" 



  - triggers: 
    - "\\fr12 "
    - "\\f12 "
    - "\\frac12 "
    replace: "\\frac{1}{2}"

  - trigger: "^^ "
    replace: "^{$|$}"

  - trigger: "__ "
    replace: "_{$|$}"

  - trigger: "\\sm "
    replace: "\\setminus"
